### ISSUE TITLE
Use simpler HTML for <picture>

### ISSUE THREAD

**Issue by zcorpan** [rosell-dk/dom-util-for-webp#9]
* Don't copy any attributes from the `img` to the picture. They are not needed and several are invalid (alt, width, height).
* Omit the jpg `source`. It is redundant with the `img`.

**Comment by rosell-dk** [comment]
Yes, it seems you are right in both cases.

I'm surprised to see that styles put on the img tag also takes effect when a source tag is picked, without it being defined in the picture tag.

**Comment by zcorpan** [comment]
Yep, it's still the `img` that shows the selected image. The `picture` is just a wrapper basically.
